tasks:
  - name: Setup
    before: |
      npm i
      npm run build
      npm run add
      assertible-to-junit "$(cat ./example-jsons/single-test.json)" "$(cat ./example-jsons/tests.json)"
      xunit-viewer -r test-report.xml -w -s -p 5050
